server: 
  port: 1111
  
app:
  upload:
    path: images


spring:
  servlet:
    multipart:
      max-file-size: 512KB
      max-request-size: 512KB
    
---
spring:
  profiles:
    active: production

---
spring:
  profiles: dev
  spring:
    main:
      allow-bean-definition-overriding: true
  datasource:
    url:  jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: Wanwork0987
  jpa: 
    properties: 
      hibernate:  
        format_sql: true
    show-sql : true
    hibernate.ddl-auto: update

---
spring:
  profiles: test
  datasource:
    url:  jdbc:h2:mem:mynaem
    username: myname
    password: hlr4321
  jpa: 
    properties: 
      hibernate:  
        format_sql: true
    show-sql : true
    hibernate.ddl-auto: create-drop
  h2:
    console:
      enabled: true
---
spring:
  profiles: production

  datasource:
    url:  jdbc:postgresql://john.db.elephantsql.com:5432/tjjkwgei 
    username: tjjkwgei
    password: fYxYBxAwUO0whJ2jrpaO5jRuNkeH78aN 
  jpa: 
    properties: 
      hibernate:  
        format_sql: true
    show-sql : true
    hibernate.ddl-auto: update
    
server: 
  port: 1111